version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}marketplace.api
    container_name: Marketplace.Backend
    ports:
      - "5001:80"
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      # Mac
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
# Windows
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

      # Mac    
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: ./Marketplace.API/Dockerfile
    depends_on: 
      - sqlserver
    restart: always
  sqlserver:
    image:  ${DOCKER_REGISTRY-}marketplace.db
    container_name: Marketplace.Database
    build:
      context: Marketplace.Database
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=@SecurePassword!
      - ACCEPT_EULA=Y
    expose:
      - 1433
    ports:
      - "14332:1433"
    volumes:
      - db_data:/var/opt/mssql
    restart: unless-stopped
volumes: 
  db_data:
